<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container69Pwdtz\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container69Pwdtz/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/Container69Pwdtz.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\Container69Pwdtz\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \Container69Pwdtz\App_KernelEnvDebugContainer([
    'container.build_hash' => '69Pwdtz',
    'container.build_id' => 'bc391e4d',
    'container.build_time' => 1687108824,
], __DIR__.\DIRECTORY_SEPARATOR.'Container69Pwdtz');
