<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fcd7nlService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._Fcd7nl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Fcd7nl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'consultum' => ['privates', '.errored..service_locator._Fcd7nl.App\\Entity\\Consulta', NULL, 'Cannot autowire service ".service_locator._Fcd7nl": it references class "App\\Entity\\Consulta" but no such service exists.'],
        ], [
            'consultum' => 'App\\Entity\\Consulta',
        ]);
    }
}
