<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KClv756Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.KClv756' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KClv756'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartManager' => ['privates', 'App\\Manager\\CartManager', 'getCartManagerService', true],
            'producto' => ['privates', '.errored..service_locator.KClv756.App\\Entity\\Producto', NULL, 'Cannot autowire service ".service_locator.KClv756": it references class "App\\Entity\\Producto" but no such service exists.'],
        ], [
            'cartManager' => 'App\\Manager\\CartManager',
            'producto' => 'App\\Entity\\Producto',
        ]);
    }
}
