<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9hfbO5MService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.9hfbO5M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9hfbO5M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'consultaRepository' => ['privates', 'App\\Repository\\ConsultaRepository', 'getConsultaRepositoryService', true],
        ], [
            'consultaRepository' => 'App\\Repository\\ConsultaRepository',
        ]);
    }
}
