<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CsdzdLSService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.CsdzdLS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CsdzdLS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'novedade' => ['privates', '.errored..service_locator.CsdzdLS.App\\Entity\\Novedades', NULL, 'Cannot autowire service ".service_locator.CsdzdLS": it references class "App\\Entity\\Novedades" but no such service exists.'],
        ], [
            'novedade' => 'App\\Entity\\Novedades',
        ]);
    }
}
