<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FNXIrlEService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.fNXIrlE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fNXIrlE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clienteRepository' => ['privates', 'App\\Repository\\ClienteRepository', 'getClienteRepositoryService', true],
            'estadoRepository' => ['privates', 'App\\Repository\\EstadoRepository', 'getEstadoRepositoryService', true],
            'orderFactory' => ['privates', 'App\\Factory\\OrderFactory', 'getOrderFactoryService', true],
            'orderItemRepository' => ['privates', 'App\\Repository\\OrderItemRepository', 'getOrderItemRepositoryService', true],
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'pedido' => ['privates', '.errored..service_locator.fNXIrlE.App\\Entity\\Pedido', NULL, 'Cannot autowire service ".service_locator.fNXIrlE": it references class "App\\Entity\\Pedido" but no such service exists.'],
            'pedidoRepository' => ['privates', 'App\\Repository\\PedidoRepository', 'getPedidoRepositoryService', true],
        ], [
            'clienteRepository' => 'App\\Repository\\ClienteRepository',
            'estadoRepository' => 'App\\Repository\\EstadoRepository',
            'orderFactory' => 'App\\Factory\\OrderFactory',
            'orderItemRepository' => 'App\\Repository\\OrderItemRepository',
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'pedido' => 'App\\Entity\\Pedido',
            'pedidoRepository' => 'App\\Repository\\PedidoRepository',
        ]);
    }
}
