<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriaRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CategoriaRepository' shared autowired service.
     *
     * @return \App\Repository\CategoriaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CategoriaRepository'] = new \App\Repository\CategoriaRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
