<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClienteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.8Qyp059.App\Entity\Cliente' shared service.
     *
     * @return \App\Entity\Cliente
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8Qyp059": it references class "App\\Entity\\Cliente" but no such service exists.');
    }
}
