<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Form\\AddToCartType' => ['privates', 'App\\Form\\AddToCartType', 'getAddToCartTypeService', true],
            'App\\Form\\CartItemType' => ['privates', 'App\\Form\\CartItemType', 'getCartItemTypeService', true],
            'App\\Form\\CartType' => ['privates', 'App\\Form\\CartType', 'getCartTypeService', true],
            'App\\Form\\CategoriaType' => ['privates', 'App\\Form\\CategoriaType', 'getCategoriaTypeService', true],
            'App\\Form\\ClienteType' => ['privates', 'App\\Form\\ClienteType', 'getClienteTypeService', true],
            'App\\Form\\ConsultaType' => ['privates', 'App\\Form\\ConsultaType', 'getConsultaTypeService', true],
            'App\\Form\\ConsultaUsuariosType' => ['privates', 'App\\Form\\ConsultaUsuariosType', 'getConsultaUsuariosTypeService', true],
            'App\\Form\\NovedadesType' => ['privates', 'App\\Form\\NovedadesType', 'getNovedadesTypeService', true],
            'App\\Form\\PedidoType' => ['privates', 'App\\Form\\PedidoType', 'getPedidoTypeService', true],
            'App\\Form\\PedidoTypeAdmin' => ['privates', 'App\\Form\\PedidoTypeAdmin', 'getPedidoTypeAdminService', true],
            'App\\Form\\ProductoType' => ['privates', 'App\\Form\\ProductoType', 'getProductoTypeService', true],
            'App\\Form\\RegistrationFormType' => ['privates', 'App\\Form\\RegistrationFormType', 'getRegistrationFormTypeService', true],
            'App\\Form\\RoleType' => ['privates', 'App\\Form\\RoleType', 'getRoleTypeService', true],
            'App\\Form\\StockType' => ['privates', 'App\\Form\\StockType', 'getStockTypeService', true],
            'App\\Form\\User1Type' => ['privates', 'App\\Form\\User1Type', 'getUser1TypeService', true],
            'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['services', '.container.private.form.type.file', 'get_Container_Private_Form_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
            'Vich\\UploaderBundle\\Form\\Type\\VichFileType' => ['services', 'vich_uploader.form.type.file', 'getVichUploader_Form_Type_FileService', true],
            'Vich\\UploaderBundle\\Form\\Type\\VichImageType' => ['services', 'vich_uploader.form.type.image', 'getVichUploader_Form_Type_ImageService', true],
        ], [
            'App\\Form\\AddToCartType' => '?',
            'App\\Form\\CartItemType' => '?',
            'App\\Form\\CartType' => '?',
            'App\\Form\\CategoriaType' => '?',
            'App\\Form\\ClienteType' => '?',
            'App\\Form\\ConsultaType' => '?',
            'App\\Form\\ConsultaUsuariosType' => '?',
            'App\\Form\\NovedadesType' => '?',
            'App\\Form\\PedidoType' => '?',
            'App\\Form\\PedidoTypeAdmin' => '?',
            'App\\Form\\ProductoType' => '?',
            'App\\Form\\RegistrationFormType' => '?',
            'App\\Form\\RoleType' => '?',
            'App\\Form\\StockType' => '?',
            'App\\Form\\User1Type' => '?',
            'App\\Form\\UserType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
            'Vich\\UploaderBundle\\Form\\Type\\VichFileType' => '?',
            'Vich\\UploaderBundle\\Form\\Type\\VichImageType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
        }, 5), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ?? ($container->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ?? ($container->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\ResolvedFormTypeFactory());
    }
}
