<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNovedadesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Novedades\NovedadesController' shared autowired service.
     *
     * @return \App\Controller\Novedades\NovedadesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Novedades\\NovedadesController'] = $instance = new \App\Controller\Novedades\NovedadesController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\Novedades\\NovedadesController', $container));

        return $instance;
    }
}
