<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNovedadesService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.CsdzdLS.App\Entity\Novedades' shared service.
     *
     * @return \App\Entity\Novedades
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CsdzdLS": it references class "App\\Entity\\Novedades" but no such service exists.');
    }
}
