<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProducto2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.KClv756.App\Entity\Producto' shared service.
     *
     * @return \App\Entity\Producto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KClv756": it references class "App\\Entity\\Producto" but no such service exists.');
    }
}
