<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductoTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ProductoType' shared autowired service.
     *
     * @return \App\Form\ProductoType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ProductoType'] = new \App\Form\ProductoType();
    }
}
