<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Profile\ProfileController' shared autowired service.
     *
     * @return \App\Controller\Profile\ProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Profile\\ProfileController'] = $instance = new \App\Controller\Profile\ProfileController(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\ClienteRepository'] ?? $container->load('getClienteRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\Profile\\ProfileController', $container));

        return $instance;
    }
}
