<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedido3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.fNXIrlE.App\Entity\Pedido' shared service.
     *
     * @return \App\Entity\Pedido
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fNXIrlE": it references class "App\\Entity\\Pedido" but no such service exists.');
    }
}
