<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RoleType' shared autowired service.
     *
     * @return \App\Form\RoleType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RoleType'] = new \App\Form\RoleType();
    }
}
