<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveExpiredCartsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\RemoveExpiredCartsCommand' shared autowired service.
     *
     * @return \App\Command\RemoveExpiredCartsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\RemoveExpiredCartsCommand'] = $instance = new \App\Command\RemoveExpiredCartsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService')));

        $instance->setName('app:remove-expired-carts');

        return $instance;
    }
}
