<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonycasts_VerifyEmail_HelperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'symfonycasts.verify_email.helper' shared service.
     *
     * @return \SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['symfonycasts.verify_email.helper'] = new \SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelper(($container->services['router'] ?? $container->getRouterService()), new \Symfony\Component\HttpKernel\UriSigner($container->getEnv('APP_SECRET'), 'signature'), new \SymfonyCasts\Bundle\VerifyEmail\Util\VerifyEmailQueryUtility(), new \SymfonyCasts\Bundle\VerifyEmail\Generator\VerifyEmailTokenGenerator($container->getEnv('APP_SECRET')), 3600);
    }
}
