<?php

namespace ContainerXEcUGjd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\StockType' shared autowired service.
     *
     * @return \App\Form\StockType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\StockType'] = new \App\Form\StockType();
    }
}
