<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SVJ3dZEService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.SVJ3dZE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SVJ3dZE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productoRepository' => ['privates', 'App\\Repository\\ProductoRepository', 'getProductoRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'productoRepository' => 'App\\Repository\\ProductoRepository',
            'slugger' => '?',
        ]);
    }
}
