<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jf0YdQService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.Jf0YdQ_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Jf0YdQ_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartManager' => ['privates', 'App\\Manager\\CartManager', 'getCartManagerService', true],
            'estadoRepository' => ['privates', 'App\\Repository\\EstadoRepository', 'getEstadoRepositoryService', true],
            'pedidoRepository' => ['privates', 'App\\Repository\\PedidoRepository', 'getPedidoRepositoryService', true],
            'producto' => ['privates', '.errored..service_locator.Jf0YdQ_.App\\Entity\\Producto', NULL, 'Cannot autowire service ".service_locator.Jf0YdQ_": it references class "App\\Entity\\Producto" but no such service exists.'],
        ], [
            'cartManager' => 'App\\Manager\\CartManager',
            'estadoRepository' => 'App\\Repository\\EstadoRepository',
            'pedidoRepository' => 'App\\Repository\\PedidoRepository',
            'producto' => 'App\\Entity\\Producto',
        ]);
    }
}
