<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EeM5QUKService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.eeM5QUK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eeM5QUK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'consultaRepository' => ['privates', 'App\\Repository\\ConsultaRepository', 'getConsultaRepositoryService', true],
            'consultum' => ['privates', '.errored..service_locator.eeM5QUK.App\\Entity\\Consulta', NULL, 'Cannot autowire service ".service_locator.eeM5QUK": it references class "App\\Entity\\Consulta" but no such service exists.'],
        ], [
            'consultaRepository' => 'App\\Repository\\ConsultaRepository',
            'consultum' => 'App\\Entity\\Consulta',
        ]);
    }
}
