<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZQ0RuFnService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.zQ0RuFn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zQ0RuFn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
            'user' => ['privates', '.errored..service_locator.zQ0RuFn.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.zQ0RuFn": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'encoder' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
