<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O7MMxHXService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.O7MMxHX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O7MMxHX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'role' => ['privates', '.errored..service_locator.O7MMxHX.App\\Entity\\Role', NULL, 'Cannot autowire service ".service_locator.O7MMxHX": it references class "App\\Entity\\Role" but no such service exists.'],
        ], [
            'role' => 'App\\Entity\\Role',
        ]);
    }
}
