<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultaControllerService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the public 'App\Controller\Consulta\ConsultaController' shared autowired service.
     *
     * @return \App\Controller\Consulta\ConsultaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Consulta/ConsultaController.php';

        $container->services['App\\Controller\\Consulta\\ConsultaController'] = $instance = new \App\Controller\Consulta\ConsultaController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\Consulta\\ConsultaController', $container));

        return $instance;
    }
}
