<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoria3Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hiS8Amk.App\Entity\Categoria' shared service.
     *
     * @return \App\Entity\Categoria
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hiS8Amk": it references class "App\\Entity\\Categoria" but no such service exists.');
    }
}
