<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultaService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._Fcd7nl.App\Entity\Consulta' shared service.
     *
     * @return \App\Entity\Consulta
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._Fcd7nl": it references class "App\\Entity\\Consulta" but no such service exists.');
    }
}
