<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkdown_ParserService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the public 'markdown.parser' shared service.
     *
     * @return \Knp\Bundle\MarkdownBundle\Parser\Preset\Max
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/michelf/php-markdown/Michelf/MarkdownInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/michelf/php-markdown/Michelf/Markdown.php';
        include_once \dirname(__DIR__, 4).'/vendor/michelf/php-markdown/Michelf/MarkdownExtra.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-markdown-bundle/MarkdownParserInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-markdown-bundle/Parser/MarkdownParser.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-markdown-bundle/Parser/Preset/Max.php';

        return $container->services['markdown.parser'] = new \Knp\Bundle\MarkdownBundle\Parser\Preset\Max();
    }
}
