<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNovedades2Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.k9qG9S0.App\Entity\Novedades' shared service.
     *
     * @return \App\Entity\Novedades
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.k9qG9S0": it references class "App\\Entity\\Novedades" but no such service exists.');
    }
}
