<?php

namespace Container69Pwdtz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNovedadesTypeService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private 'App\Form\NovedadesType' shared autowired service.
     *
     * @return \App\Form\NovedadesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/NovedadesType.php';

        return $container->privates['App\\Form\\NovedadesType'] = new \App\Form\NovedadesType();
    }
}
