<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEcUGjd\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEcUGjd/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXEcUGjd.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXEcUGjd\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXEcUGjd\App_KernelProdContainer([
    'container.build_hash' => 'XEcUGjd',
    'container.build_id' => 'cb56f107',
    'container.build_time' => 1686990977,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEcUGjd');
