<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \App\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'categorias', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'imageName', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'imageSize', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'cantidadProducto', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'pedidos', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'items'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'categorias', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'imageName', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'imageSize', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'cantidadProducto', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'pedidos', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'items'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setImageName(?string $imageName): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageName', [$imageName]);

        parent::setImageName($imageName);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageName', []);

        return parent::getImageName();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageSize(?int $imageSize): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageSize', [$imageSize]);

        parent::setImageSize($imageSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageSize(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageSize', []);

        return parent::getImageSize();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorias(): ?\App\Entity\Categoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorias', []);

        return parent::getCategorias();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorias(?\App\Entity\Categoria $categorias): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorias', [$categorias]);

        return parent::setCategorias($categorias);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock(): ?\App\Entity\Stock
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock(?\App\Entity\Stock $stock): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio(float $precio): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile($imageFile): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$imageFile]);

        parent::setImageFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadProducto', []);

        return parent::getCantidadProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadProducto($cantidadProducto): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadProducto', [$cantidadProducto]);

        parent::setCantidadProducto($cantidadProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPedidos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPedidos', []);

        return parent::getPedidos();
    }

    /**
     * {@inheritDoc}
     */
    public function addPedido(\App\Entity\Pedido $pedido): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPedido', [$pedido]);

        return parent::addPedido($pedido);
    }

    /**
     * {@inheritDoc}
     */
    public function removePedido(\App\Entity\Pedido $pedido): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePedido', [$pedido]);

        return parent::removePedido($pedido);
    }

    /**
     * {@inheritDoc}
     */
    public function getItems(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', []);

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addItem(\App\Entity\OrderItem $item): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItem', [$item]);

        return parent::addItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItem(\App\Entity\OrderItem $item): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItem', [$item]);

        return parent::removeItem($item);
    }

}
